[build]
  publish = "." # La carpeta donde se encuentra tu index.html y otros archivos estáticos (el punto significa la raíz del repositorio)
  command = "npm install && npm install --prefix netlify/functions" # Instala las dependencias del proyecto principal y luego las de la función

[functions]
  directory = "netlify/functions" # La carpeta donde se encuentran tus funciones de Netlify
  node_bundler = "esbuild" # Recomendado para un rendimiento más rápido

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
