[build]
  # Comando de construcción para instalar dependencias de Node.js
  command = "npm install"
  # Directorio de publicación de tu sitio web (donde está index.html)
  publish = "."

[functions]
  # Directorio donde se encuentran tus funciones de Netlify
  directory = "netlify/functions"
