[build]
  publish = "." # La carpeta donde se encuentra tu index.html y otros archivos estáticos (el punto significa la raíz del repositorio)
  command = "npm install" # Instala las dependencias de Node.js

[functions]
  directory = "netlify/functions" # La carpeta donde se encuentran tus funciones de Netlify (asumiendo que está dentro de la raíz del repositorio)
  node_bundler = "esbuild" # Recomendado para un rendimiento más rápido

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
