[build]
  publish = "." # La carpeta donde se encuentra tu index.html y otros archivos est치ticos
  command = "npm install && npm install --prefix netlify/functions" # Instala dependencias del proyecto y luego las de la funci칩n

[functions]
  directory = "netlify/functions" # La carpeta donde se encuentran tus funciones de Netlify
  node_bundler = "esbuild" # Recomendado para un rendimiento m치s r치pido

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
